<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
use App\Models\BidangKeilmuan;

class DosenSeeder extends Seeder
{
	public function run()
	{
		$bidang_keilmuan = new BidangKeilmuan;
		$data = $bidang_keilmuan->findAll();
		$id_bidang_keilmuan = [];
		foreach($data as $item) {
			$id_bidang_keilmuan[] = $item['id_bidang_keilmuan'];
		}
		$data = [
			[
			'id_dosen'           => "dos_".date("ymdhis")."_".uniqid(),
			'nama_lengkap'       => static::faker()->name,
			'gelar_depan'        => static::faker()->word,
			'gelar_belakang'     => static::faker()->word,
			'nip'                => static::faker()->randomNumber(9, true),
			'tempat_lahir'       => static::faker()->cityPrefix,
			'tanggal_lahir'      => static::faker()->date("Y-m-d H:i:s"),
			'jenkel'             => static::faker()->randomElements(['L', 'P']),
			'alamat'             => static::faker()->city,
			'pos_el'             => static::faker()->email,
			'no_hp'              => static::faker()->e164PhoneNumber,
			'npwp'               => static::faker()->randomNumber(9, true),
			'no_ktp'             => static::faker()->randomNumber(9, true),
			'nama_bank'          => 'BCA',
			'jamsostek'          => static::faker()->randomNumber(9, true),
			'bpjs_kes'           => static::faker()->randomNumber(9, true),
			'yadapen'            => static::faker()->randomNumber(6, true),
			'asuransi'           => static::faker()->randomNumber(9, true),
			'nidn'               => static::faker()->randomNumber(9, true),
			'id_bidang_keilmuan'        => static::faker()->randomElements($id_bidang_keilmuan),
			'tag_struktural'     => static::faker()->word,
			'tag_fungsional'     => static::faker()->word,
			'tag_admin_fakultas' => static::faker()->word,
			'created_at'         => date("Y-m-d H:i:s"),
			'created_by'         => 'Admin'
			],
			[
			'id_dosen'           => "dos_".date("ymdhis")."_".uniqid(),
			'nama_lengkap'       => static::faker()->name,
			'gelar_depan'        => static::faker()->word,
			'gelar_belakang'     => static::faker()->word,
			'nip'                => static::faker()->randomNumber(9, true),
			'tempat_lahir'       => static::faker()->cityPrefix,
			'tanggal_lahir'      => static::faker()->date("Y-m-d H:i:s"),
			'jenkel'             => static::faker()->randomElements(['L', 'P']),
			'alamat'             => static::faker()->city,
			'pos_el'             => static::faker()->email,
			'no_hp'              => static::faker()->e164PhoneNumber,
			'npwp'               => static::faker()->randomNumber(9, true),
			'no_ktp'             => static::faker()->randomNumber(9, true),
			'nama_bank'          => 'BCA',
			'jamsostek'          => static::faker()->randomNumber(9, true),
			'bpjs_kes'           => static::faker()->randomNumber(9, true),
			'yadapen'            => static::faker()->randomNumber(6, true),
			'asuransi'           => static::faker()->randomNumber(9, true),
			'nidn'               => static::faker()->randomNumber(9, true),
			'id_bidang_keilmuan'        => static::faker()->randomElements($id_bidang_keilmuan),
			'tag_struktural'     => static::faker()->word,
			'tag_fungsional'     => static::faker()->word,
			'tag_admin_fakultas' => static::faker()->word,
			'created_at'         => date("Y-m-d H:i:s"),
			'created_by'         => 'Admin'
			],
			[
			'id_dosen'           => "dos_".date("ymdhis")."_".uniqid(),
			'nama_lengkap'       => static::faker()->name,
			'gelar_depan'        => static::faker()->word,
			'gelar_belakang'     => static::faker()->word,
			'nip'                => static::faker()->randomNumber(9, true),
			'tempat_lahir'       => static::faker()->cityPrefix,
			'tanggal_lahir'      => static::faker()->date("Y-m-d H:i:s"),
			'jenkel'             => static::faker()->randomElements(['L', 'P']),
			'alamat'             => static::faker()->city,
			'pos_el'             => static::faker()->email,
			'no_hp'              => static::faker()->e164PhoneNumber,
			'npwp'               => static::faker()->randomNumber(9, true),
			'no_ktp'             => static::faker()->randomNumber(9, true),
			'nama_bank'          => 'BCA',
			'jamsostek'          => static::faker()->randomNumber(9, true),
			'bpjs_kes'           => static::faker()->randomNumber(9, true),
			'yadapen'            => static::faker()->randomNumber(6, true),
			'asuransi'           => static::faker()->randomNumber(9, true),
			'nidn'               => static::faker()->randomNumber(9, true),
			'id_bidang_keilmuan'        => static::faker()->randomElements($id_bidang_keilmuan),
			'tag_struktural'     => static::faker()->word,
			'tag_fungsional'     => static::faker()->word,
			'tag_admin_fakultas' => static::faker()->word,
			'created_at'         => date("Y-m-d H:i:s"),
			'created_by'         => 'Admin'
			],
			[
			'id_dosen'           => "dos_".date("ymdhis")."_".uniqid(),
			'nama_lengkap'       => static::faker()->name,
			'gelar_depan'        => static::faker()->word,
			'gelar_belakang'     => static::faker()->word,
			'nip'                => static::faker()->randomNumber(9, true),
			'tempat_lahir'       => static::faker()->cityPrefix,
			'tanggal_lahir'      => static::faker()->date("Y-m-d H:i:s"),
			'jenkel'             => static::faker()->randomElements(['L', 'P']),
			'alamat'             => static::faker()->city,
			'pos_el'             => static::faker()->email,
			'no_hp'              => static::faker()->e164PhoneNumber,
			'npwp'               => static::faker()->randomNumber(9, true),
			'no_ktp'             => static::faker()->randomNumber(9, true),
			'nama_bank'          => 'BCA',
			'jamsostek'          => static::faker()->randomNumber(9, true),
			'bpjs_kes'           => static::faker()->randomNumber(9, true),
			'yadapen'            => static::faker()->randomNumber(6, true),
			'asuransi'           => static::faker()->randomNumber(9, true),
			'nidn'               => static::faker()->randomNumber(9, true),
			'id_bidang_keilmuan'        => static::faker()->randomElements($id_bidang_keilmuan),
			'tag_struktural'     => static::faker()->word,
			'tag_fungsional'     => static::faker()->word,
			'tag_admin_fakultas' => static::faker()->word,
			'created_at'         => date("Y-m-d H:i:s"),
			'created_by'         => 'Admin'
			],
			[
			'id_dosen'           => "dos_".date("ymdhis")."_".uniqid(),
			'nama_lengkap'       => static::faker()->name,
			'gelar_depan'        => static::faker()->word,
			'gelar_belakang'     => static::faker()->word,
			'nip'                => static::faker()->randomNumber(9, true),
			'tempat_lahir'       => static::faker()->cityPrefix,
			'tanggal_lahir'      => static::faker()->date("Y-m-d H:i:s"),
			'jenkel'             => static::faker()->randomElements(['L', 'P']),
			'alamat'             => static::faker()->city,
			'pos_el'             => static::faker()->email,
			'no_hp'              => static::faker()->e164PhoneNumber,
			'npwp'               => static::faker()->randomNumber(9, true),
			'no_ktp'             => static::faker()->randomNumber(9, true),
			'nama_bank'          => 'BCA',
			'jamsostek'          => static::faker()->randomNumber(9, true),
			'bpjs_kes'           => static::faker()->randomNumber(9, true),
			'yadapen'            => static::faker()->randomNumber(6, true),
			'asuransi'           => static::faker()->randomNumber(9, true),
			'nidn'               => static::faker()->randomNumber(9, true),
			'id_bidang_keilmuan'        => static::faker()->randomElements($id_bidang_keilmuan),
			'tag_struktural'     => static::faker()->word,
			'tag_fungsional'     => static::faker()->word,
			'tag_admin_fakultas' => static::faker()->word,
			'created_at'         => date("Y-m-d H:i:s"),
			'created_by'         => 'Admin'
			],
			[
			'id_dosen'           => "dos_".date("ymdhis")."_".uniqid(),
			'nama_lengkap'       => static::faker()->name,
			'gelar_depan'        => static::faker()->word,
			'gelar_belakang'     => static::faker()->word,
			'nip'                => static::faker()->randomNumber(9, true),
			'tempat_lahir'       => static::faker()->cityPrefix,
			'tanggal_lahir'      => static::faker()->date("Y-m-d H:i:s"),
			'jenkel'             => static::faker()->randomElements(['L', 'P']),
			'alamat'             => static::faker()->city,
			'pos_el'             => static::faker()->email,
			'no_hp'              => static::faker()->e164PhoneNumber,
			'npwp'               => static::faker()->randomNumber(9, true),
			'no_ktp'             => static::faker()->randomNumber(9, true),
			'nama_bank'          => 'BCA',
			'jamsostek'          => static::faker()->randomNumber(9, true),
			'bpjs_kes'           => static::faker()->randomNumber(9, true),
			'yadapen'            => static::faker()->randomNumber(6, true),
			'asuransi'           => static::faker()->randomNumber(9, true),
			'nidn'               => static::faker()->randomNumber(9, true),
			'id_bidang_keilmuan'        => static::faker()->randomElements($id_bidang_keilmuan),
			'tag_struktural'     => static::faker()->word,
			'tag_fungsional'     => static::faker()->word,
			'tag_admin_fakultas' => static::faker()->word,
			'created_at'         => date("Y-m-d H:i:s"),
			'created_by'         => 'Admin'
			],
			[
			'id_dosen'           => "dos_".date("ymdhis")."_".uniqid(),
			'nama_lengkap'       => static::faker()->name,
			'gelar_depan'        => static::faker()->word,
			'gelar_belakang'     => static::faker()->word,
			'nip'                => static::faker()->randomNumber(9, true),
			'tempat_lahir'       => static::faker()->cityPrefix,
			'tanggal_lahir'      => static::faker()->date("Y-m-d H:i:s"),
			'jenkel'             => static::faker()->randomElements(['L', 'P']),
			'alamat'             => static::faker()->city,
			'pos_el'             => static::faker()->email,
			'no_hp'              => static::faker()->e164PhoneNumber,
			'npwp'               => static::faker()->randomNumber(9, true),
			'no_ktp'             => static::faker()->randomNumber(9, true),
			'nama_bank'          => 'BCA',
			'jamsostek'          => static::faker()->randomNumber(9, true),
			'bpjs_kes'           => static::faker()->randomNumber(9, true),
			'yadapen'            => static::faker()->randomNumber(6, true),
			'asuransi'           => static::faker()->randomNumber(9, true),
			'nidn'               => static::faker()->randomNumber(9, true),
			'id_bidang_keilmuan'        => static::faker()->randomElements($id_bidang_keilmuan),
			'tag_struktural'     => static::faker()->word,
			'tag_fungsional'     => static::faker()->word,
			'tag_admin_fakultas' => static::faker()->word,
			'created_at'         => date("Y-m-d H:i:s"),
			'created_by'         => 'Admin'
			],
			[
			'id_dosen'           => "dos_".date("ymdhis")."_".uniqid(),
			'nama_lengkap'       => static::faker()->name,
			'gelar_depan'        => static::faker()->word,
			'gelar_belakang'     => static::faker()->word,
			'nip'                => static::faker()->randomNumber(9, true),
			'tempat_lahir'       => static::faker()->cityPrefix,
			'tanggal_lahir'      => static::faker()->date("Y-m-d H:i:s"),
			'jenkel'             => static::faker()->randomElements(['L', 'P']),
			'alamat'             => static::faker()->city,
			'pos_el'             => static::faker()->email,
			'no_hp'              => static::faker()->e164PhoneNumber,
			'npwp'               => static::faker()->randomNumber(9, true),
			'no_ktp'             => static::faker()->randomNumber(9, true),
			'nama_bank'          => 'BCA',
			'jamsostek'          => static::faker()->randomNumber(9, true),
			'bpjs_kes'           => static::faker()->randomNumber(9, true),
			'yadapen'            => static::faker()->randomNumber(6, true),
			'asuransi'           => static::faker()->randomNumber(9, true),
			'nidn'               => static::faker()->randomNumber(9, true),
			'id_bidang_keilmuan'        => static::faker()->randomElements($id_bidang_keilmuan),
			'tag_struktural'     => static::faker()->word,
			'tag_fungsional'     => static::faker()->word,
			'tag_admin_fakultas' => static::faker()->word,
			'created_at'         => date("Y-m-d H:i:s"),
			'created_by'         => 'Admin'
			],
			[
			'id_dosen'           => "dos_".date("ymdhis")."_".uniqid(),
			'nama_lengkap'       => static::faker()->name,
			'gelar_depan'        => static::faker()->word,
			'gelar_belakang'     => static::faker()->word,
			'nip'                => static::faker()->randomNumber(9, true),
			'tempat_lahir'       => static::faker()->cityPrefix,
			'tanggal_lahir'      => static::faker()->date("Y-m-d H:i:s"),
			'jenkel'             => static::faker()->randomElements(['L', 'P']),
			'alamat'             => static::faker()->city,
			'pos_el'             => static::faker()->email,
			'no_hp'              => static::faker()->e164PhoneNumber,
			'npwp'               => static::faker()->randomNumber(9, true),
			'no_ktp'             => static::faker()->randomNumber(9, true),
			'nama_bank'          => 'BCA',
			'jamsostek'          => static::faker()->randomNumber(9, true),
			'bpjs_kes'           => static::faker()->randomNumber(9, true),
			'yadapen'            => static::faker()->randomNumber(6, true),
			'asuransi'           => static::faker()->randomNumber(9, true),
			'nidn'               => static::faker()->randomNumber(9, true),
			'id_bidang_keilmuan'        => static::faker()->randomElements($id_bidang_keilmuan),
			'tag_struktural'     => static::faker()->word,
			'tag_fungsional'     => static::faker()->word,
			'tag_admin_fakultas' => static::faker()->word,
			'created_at'         => date("Y-m-d H:i:s"),
			'created_by'         => 'Admin'
			],
			[
			'id_dosen'           => "dos_".date("ymdhis")."_".uniqid(),
			'nama_lengkap'       => static::faker()->name,
			'gelar_depan'        => static::faker()->word,
			'gelar_belakang'     => static::faker()->word,
			'nip'                => static::faker()->randomNumber(9, true),
			'tempat_lahir'       => static::faker()->cityPrefix,
			'tanggal_lahir'      => static::faker()->date("Y-m-d H:i:s"),
			'jenkel'             => static::faker()->randomElements(['L', 'P']),
			'alamat'             => static::faker()->city,
			'pos_el'             => static::faker()->email,
			'no_hp'              => static::faker()->e164PhoneNumber,
			'npwp'               => static::faker()->randomNumber(9, true),
			'no_ktp'             => static::faker()->randomNumber(9, true),
			'nama_bank'          => 'BCA',
			'jamsostek'          => static::faker()->randomNumber(9, true),
			'bpjs_kes'           => static::faker()->randomNumber(9, true),
			'yadapen'            => static::faker()->randomNumber(6, true),
			'asuransi'           => static::faker()->randomNumber(9, true),
			'nidn'               => static::faker()->randomNumber(9, true),
			'id_bidang_keilmuan'        => static::faker()->randomElements($id_bidang_keilmuan),
			'tag_struktural'     => static::faker()->word,
			'tag_fungsional'     => static::faker()->word,
			'tag_admin_fakultas' => static::faker()->word,
			'created_at'         => date("Y-m-d H:i:s"),
			'created_by'         => 'Admin'
			],
			[
			'id_dosen'           => "dos_".date("ymdhis")."_".uniqid(),
			'nama_lengkap'       => static::faker()->name,
			'gelar_depan'        => static::faker()->word,
			'gelar_belakang'     => static::faker()->word,
			'nip'                => static::faker()->randomNumber(9, true),
			'tempat_lahir'       => static::faker()->cityPrefix,
			'tanggal_lahir'      => static::faker()->date("Y-m-d H:i:s"),
			'jenkel'             => static::faker()->randomElements(['L', 'P']),
			'alamat'             => static::faker()->city,
			'pos_el'             => static::faker()->email,
			'no_hp'              => static::faker()->e164PhoneNumber,
			'npwp'               => static::faker()->randomNumber(9, true),
			'no_ktp'             => static::faker()->randomNumber(9, true),
			'nama_bank'          => 'BCA',
			'jamsostek'          => static::faker()->randomNumber(9, true),
			'bpjs_kes'           => static::faker()->randomNumber(9, true),
			'yadapen'            => static::faker()->randomNumber(6, true),
			'asuransi'           => static::faker()->randomNumber(9, true),
			'nidn'               => static::faker()->randomNumber(9, true),
			'id_bidang_keilmuan'        => static::faker()->randomElements($id_bidang_keilmuan),
			'tag_struktural'     => static::faker()->word,
			'tag_fungsional'     => static::faker()->word,
			'tag_admin_fakultas' => static::faker()->word,
			'created_at'         => date("Y-m-d H:i:s"),
			'created_by'         => 'Admin'
			],
		];

		// Using Query Builder
		$this->db->table('ms_dosen')->insertBatch($data);
	}
}
